services:
  kafka-broker-and-controller:
    image: apache/kafka:4.0.0
    environment:
      CLUSTER_ID: 't5s3216_SCeef-9N33O12g'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'OUT_DOCKER://:9092,CONTROLLER://:9093,IN_DOCKER://kafka-broker-and-controller:9094'
      KAFKA_ADVERTISED_LISTENERS: 'OUT_DOCKER://localhost:9092,IN_DOCKER://kafka-broker-and-controller:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,OUT_DOCKER:PLAINTEXT,IN_DOCKER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'IN_DOCKER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-broker-and-controller-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - docker-network
  schema-registry:
    image: apicurio/apicurio-registry:3.0.12
    ports:
      - "8901:8080"
    depends_on:
      - kafka-broker-and-controller
    networks:
      - docker-network
  schema-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.12
    environment:
      REGISTRY_API_URL: http://localhost:8901/apis/registry/v3
    ports:
      - "8888:8080"
    depends_on:
      - schema-registry
    networks:
      - docker-network
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=safetypassword
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - docker-network
volumes:
  kafka-broker-and-controller-data:
networks:
  docker-network:
    driver: bridge
