apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
  labels:
    name: kafka-service
    tier: backend
spec:
  selector:
    name: kafka
  ports:
    - name: http
      protocol: TCP
      port: 9094
      targetPort: 9094
