apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    name: kafka-pv
spec:
  storageClassName: "" # handled by docker desktop https://stackoverflow.com/questions/67951356/where-is-kubernetes-storage-location-of-a-persistent-volume-on-docker-desktop-fo
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/kafka # mounted in docker 
  capacity:
    storage: 2Gi
  claimRef:
    name: kafka-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: default
spec:
  selector:
    matchLabels:
      name: kafka-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
