# HTTP
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
# Kafka
quarkus.kafka.devservices.enabled=false
quarkus.apicurio-registry.devservices.enabled=false
app.hostname=localhost:3000
# DB
quarkus.datasource.devservices.image-name=postgres:17
quarkus.flyway.migrate-at-start=true
# Redis
quarkus.redis.devservices.image-name=redis:8.2.3