apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: myurlshortner
      owner: myurlshortner
      secret:
        name: db-secret
      postInitSQL:
        - create database apicurio owner myurlshortner
