spring.datasource.url=${POSTGRES_URL}

app.kafka.bootstrap-servers=${KAFKA_SERVERS}
app.kafka.consumer.user-events.apicurio.registry.url=${REGISTRY_URL}

app.podname=myurlshortner-consumer
# BE Client
app.be.baseurl=http://be:8080
app.be.apikey=${API_KEY}
