spring.application.name=myurlshortner-consumer
server.port=7070

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=safetypassword

# Kafka Properties
app.kafka.bootstrap-servers=localhost:9092
app.kafka.consumer.group-id=myurlshortner-consumer
app.kafka.consumer.client-id=myurlshortner-consumer
app.kafka.consumer.user-events.apicurio.registry.url=http://localhost:8901/apis/registry/v3
app.kafka.consumer.topic-name=shortened-url-events
app.kafka.consumer.enabled=true

app.podname=local
app.be.baseurl=http://localhost:8080
app.be.apikey=${API_KEY:safetypassword}
