spring.datasource.url=${POSTGRES_URL}

app.kafka.bootstrap-servers=${KAFKA_SERVERS}
app.kafka.consumer.user-events.apicurio.registry.url=${REGISTRY_URL}
app.kafka.consumer.client-id=${HOSTNAME}

spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
app.podname=${HOSTNAME}

# BE Client
app.be.baseurl=http://myurlshortner-be-service:80
app.be.apikey=${API_KEY}
