spring.datasource.url=${POSTGRES_URL}
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.consumer.properties.apicurio.registry.url=${REGISTRY_URL}
app.podname=myurlshortner-consumer
# BE Client
app.be.baseurl=http://be:8080
app.be.apikey=${API_KEY}
