apiVersion: v1
kind: Service
metadata:
  name: myurlshortner-fe-service
  labels:
    tier: frontend
spec:
  selector:
    name: myurlshortner-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
