package org.acme.application.service.urlshortner;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

public class UniqueIdentifierCharTable {
    public static final Character[] UNIQUE_ID_CHAR_TABLE = new Character[]{
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '0',
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '-'
    };

    public static final Set<Character> UNIQUE_ID_CHAR_SET = Arrays.stream(UNIQUE_ID_CHAR_TABLE).collect(Collectors.toSet());
}
