name: Testing workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - workflow/**
jobs:
  Testing-Script:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#  Testing-Container:
#    runs-on: self-hosted
#    container:
#      image: hello-world:latest
  Testing-Actions:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v6
